# Generated by Django 4.1.2 on 2024-06-30 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='init_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='about',
            name='staff',
            field=models.JSONField(default={'name': 'darko', 'position': 'Software Enginner'}),
        ),
    ]
