# Generated by Django 4.1.2 on 2024-06-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_about_init_date_about_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='staff',
            field=models.JSONField(default="{'name': 'darko', 'position': 'Software Enginner'}"),
        ),
    ]
