# Generated by Django 4.1.2 on 2024-06-30 22:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_about_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='staff',
            field=models.JSONField(default=core.models.default_json),
        ),
    ]
