# Generated by Django 4.1.2 on 2024-06-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_about_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.FloatField(default=100, max_length=255),
        ),
    ]
